name: BossNyra CI

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show project files
        run: ls -R

      - name: Java version
        run: java -version
